services:
  resilmesh_sop_wo_elasticsearch:
    container_name: resilmesh_sop_wo_temporal-elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    image: elasticsearch:${ELASTICSEARCH_VERSION:-8.9.0}
    expose:
      - 9200
    volumes:
      - /var/lib/elasticsearch/data
    networks:
      - resilmesh_network

  resilmesh_sop_wo_postgresql:
    container_name: resilmesh_sop_wo_temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:${POSTGRESQL_VERSION:-17}
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      - resilmesh_network

  resilmesh_sop_wo_temporal:
    container_name: resilmesh_sop_wo_temporal
    depends_on:
      - resilmesh_sop_wo_postgresql
      - resilmesh_sop_wo_elasticsearch
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=resilmesh_sop_wo_temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=true
      - ES_SEEDS=resilmesh_sop_wo_temporal-elasticsearch
      - ES_VERSION=v7
    image: temporalio/auto-setup:${TEMPORAL_VERSION:-1.22.7}
    ports:
      - 7233:7233
    labels:
      kompose.volume.type: configMap
    volumes:
      - ./temporalio/dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - resilmesh_network
    healthcheck:
      test: ["CMD","tctl", "--address", "resilmesh_sop_wo_temporal:7233", "workflow", "list", "||", "exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  resilmesh_sop_wo_temporal-admin-tools:
    container_name: resilmesh_sop_wo_temporal-admin-tools
    depends_on:
      - resilmesh_sop_wo_temporal
    environment:
      - TEMPORAL_ADDRESS=resilmesh_sop_wo_temporal:7233
      - TEMPORAL_CLI_ADDRESS=resilmesh_sop_wo_temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_VERSION:-1.22.7}
    stdin_open: true
    tty: true
    networks:
      - resilmesh_network

  resilmesh_sop_wo_temporal-ui:
    container_name: resilmesh_sop_wo_temporal-ui
    depends_on:
      - resilmesh_sop_wo_temporal
    environment:
      - TEMPORAL_ADDRESS=resilmesh_sop_wo_temporal:7233
      #- TEMPORAL_CORS_ORIGINS=http://localhost:3000
      - TEMPORAL_CORS_ORIGINS=http://resilmesh_sop_wo_temporal-ui:3000
      - TEMPORAL_CSRF_COOKIE_INSECURE=true
    image: temporalio/ui:${TEMPORAL_UI_VERSION:-2.31.2}
    ports:
      - 8080:8080
    networks:
      - resilmesh_network
